hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
#    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%env(FACEBOOK_APP_ID)%'
            client_secret:       '%env(FACEBOOK_APP_SECRET)%'
            scope:               "email"
            options:
                csrf: true
                refresh_on_expire: true
                display: popup
        google:
            type:                google
            client_id:           '%env(GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(GOOGLE_CLIENT_SECRET)%'
            scope:               "email profile"
            options:
                csrf: true
                refresh_on_expire: true
                display: popup
