security:
    enable_authenticator_manager: true
#    encoders:
#        App\Entity\User:
#            algorithm: auto

    password_hashers:
#        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AuthenticationEntryPoint
#            guard:
#                authenticators:
#                    - App\Security\LoginFormAuthenticator
            json_login:
                check_path: admin_api.login
                login_path: admin.login
#            access_denied_handler: App\Handler\AuthenticationEntryPoint
            logout:
                path:   admin.logout

        main:
#            anonymous: true
            lazy: true
            provider: app_user_provider
#            custom_authenticators:

#            guard:
#                authenticators:
#                    - App\Security\LoginFormAuthenticator
            json_login:
                check_path: site_api.login
#                username_path: email
#                password_path: password
#            access_denied_handler: App\Handler\AccessDeniedHandler
            user_checker: App\Checker\AuthenticationChecker

            logout:
                path:   site.logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/moj-nalog, roles: ROLE_USER }
         - { path: /my-account, roles: ROLE_USER }
         - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_ADVANCED_USER, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
