parameters:
  site_info:
    url: '%env(resolve:SITE_URL)%'
  shop:
    list_sort:
      1: most_selled
      2: from_lowest_price
      3: from_highest_price
      4: on_sale
      5: first_new
    items_per_page:
      - 12
      - 24
      - 36
      - 48
    sort_mapping:
      1: ['p.id', 'DESC']
      2: ['p.price', 'ASC']
      3: ['p.price', 'DESC']
      4: ['p.discount', 'ASC']
      5: ['p.createdAt', 'DESC']
  badge:
    1: new
    2: discount
  file_types:
    images:
      1: 'jpg'
      2: 'jpeg'
      3: 'png'
      4: 'gif'
  cleaning:
    - pe-ly-bleach-non-chlorine
    - pe-ly-bleach
    - pe-ly-dry-clean-any-delicate
    - pe-ly-dry-clean-any-low-h
    - pe-ly-dry-clean-any-low-m
    - pe-ly-dry-clean-any-no-steam
    - pe-ly-dry-clean-any-resistant
    - pe-ly-dry-clean-any-short
    - pe-ly-dry-clean-any-solvent
    - pe-ly-dry-clean-low-heat
    - pe-ly-dry-clean-low-moisture
    - pe-ly-dry-clean-no-steam
    - pe-ly-dry-clean-not-trichlo-delicate
    - pe-ly-dry-clean-not-trichlo-resistant
    - pe-ly-dry-clean-not-trichlo
    - pe-ly-dry-clean-petro-delicate
    - pe-ly-dry-clean-petro-resistant
    - pe-ly-dry-clean-petro
    - pe-ly-dry-clean-short-cycle
    - pe-ly-dry-clean
    - pe-ly-dry-drip-shade
    - pe-ly-dry-drip
    - pe-ly-dry-flat-shade
    - pe-ly-dry-flat
    - pe-ly-dry-line-shade
    - pe-ly-dry-line
    - pe-ly-hand-wash
    - pe-ly-iron-high-not-steam
    - pe-ly-iron-high
    - pe-ly-iron-low-not-steam
    - pe-ly-iron-low
    - pe-ly-iron-med-not-steam
    - pe-ly-iron-medium
    - pe-ly-iron-not-steam
    - pe-ly-iron-steam
    - pe-ly-iron
    - pe-ly-machine-30
    - pe-ly-machine-40
    - pe-ly-machine-50
    - pe-ly-machine-60
    - pe-ly-machine-70
    - pe-ly-machine-95
    - pe-ly-machine-delicate-30
    - pe-ly-machine-delicate-40
    - pe-ly-machine-delicate-50
    - pe-ly-machine-delicate-60
    - pe-ly-machine-delicate-70
    - pe-ly-machine-delicate-95
    - pe-ly-machine-resistant-30
    - pe-ly-machine-resistant-40
    - pe-ly-machine-resistant-50
    - pe-ly-machine-resistant-60
    - pe-ly-machine-resistant-70
    - pe-ly-machine-resistant-95
    - pe-ly-machine-wash
    - pe-ly-not-bleach-1
    - pe-ly-not-dry-clean-1
    - pe-ly-not-iron
    - pe-ly-not-tumble-dry
    - pe-ly-not-wash
    - pe-ly-not-wring
    - pe-ly-tumble-dry-delicate
    - pe-ly-tumble-dry-high-delicate
    - pe-ly-tumble-dry-high-resistant
    - pe-ly-tumble-dry-high
    - pe-ly-tumble-dry-low-delicate
    - pe-ly-tumble-dry-low-resistant
    - pe-ly-tumble-dry-low
    - pe-ly-tumble-dry-med-delicate
    - pe-ly-tumble-dry-med-resistant
    - pe-ly-tumble-dry-medium
    - pe-ly-tumble-dry-no-heat-delicate
    - pe-ly-tumble-dry-no-heat-resistant
    - pe-ly-tumble-dry-no-heat
    - pe-ly-tumble-dry-resistant
    - pe-ly-tumble-dry
    - pe-ly-wring