parameters:
  site_info:
    url: '%env(resolve:SITE_URL)%'
  shop:
    list_sort:
      1: most_selled
      2: from_lowest_price
      3: from_highest_price
      4: on_sale
      5: first_new
    items_per_page:
      - 12
      - 24
      - 36
      - 48
    sort_mapping:
      most_selled: ['p.id', 'DESC']
      from_lowest_price: ['p.price', 'ASC']
      from_highest_price: ['p.price', 'DESC']
      on_sale: ['p.discount', 'ASC']
      first_new: ['p.createdAt', 'DESC']
  badge:
    1: new
    2: discount
  file_types:
    images:
      1: 'jpg'
      2: 'jpeg'
      3: 'png'
      4: 'gif'
  cleaning:
    - pe-ly-bleach-non-chlorine
    - pe-ly-bleach
    - pe-ly-dry-clean-any-delicate
    - pe-ly-dry-clean-any-low-h
    - pe-ly-dry-clean-any-low-m
    - pe-ly-dry-clean-any-no-steam
    - pe-ly-dry-clean-any-resistant
    - pe-ly-dry-clean-any-short
    - pe-ly-dry-clean-any-solvent
    - pe-ly-dry-clean-low-heat
    - pe-ly-dry-clean-low-moisture
    - pe-ly-dry-clean-no-steam
    - pe-ly-dry-clean-not-trichlo-delicate
    - pe-ly-dry-clean-not-trichlo-resistant
    - pe-ly-dry-clean-not-trichlo
    - pe-ly-dry-clean-petro-delicate
    - pe-ly-dry-clean-petro-resistant
    - pe-ly-dry-clean-petro
    - pe-ly-dry-clean-short-cycle
    - pe-ly-dry-clean
    - pe-ly-dry-drip-shade
    - pe-ly-dry-drip
    - pe-ly-dry-flat-shade
    - pe-ly-dry-flat
    - pe-ly-dry-line-shade
    - pe-ly-dry-line
    - pe-ly-hand-wash
    - pe-ly-iron-high-not-steam
    - pe-ly-iron-high
    - pe-ly-iron-low-not-steam
    - pe-ly-iron-low
    - pe-ly-iron-med-not-steam
    - pe-ly-iron-medium
    - pe-ly-iron-not-steam
    - pe-ly-iron-steam
    - pe-ly-iron
    - pe-ly-machine-30
    - pe-ly-machine-40
    - pe-ly-machine-50
    - pe-ly-machine-60
    - pe-ly-machine-70
    - pe-ly-machine-95
    - pe-ly-machine-delicate-30
    - pe-ly-machine-delicate-40
    - pe-ly-machine-delicate-50
    - pe-ly-machine-delicate-60
    - pe-ly-machine-delicate-70
    - pe-ly-machine-delicate-95
    - pe-ly-machine-resistant-30
    - pe-ly-machine-resistant-40
    - pe-ly-machine-resistant-50
    - pe-ly-machine-resistant-60
    - pe-ly-machine-resistant-70
    - pe-ly-machine-resistant-95
    - pe-ly-machine-wash
    - pe-ly-not-bleach-1
    - pe-ly-not-dry-clean-1
    - pe-ly-not-iron
    - pe-ly-not-tumble-dry
    - pe-ly-not-wash
    - pe-ly-not-wring
    - pe-ly-tumble-dry-delicate
    - pe-ly-tumble-dry-high-delicate
    - pe-ly-tumble-dry-high-resistant
    - pe-ly-tumble-dry-high
    - pe-ly-tumble-dry-low-delicate
    - pe-ly-tumble-dry-low-resistant
    - pe-ly-tumble-dry-low
    - pe-ly-tumble-dry-med-delicate
    - pe-ly-tumble-dry-med-resistant
    - pe-ly-tumble-dry-medium
    - pe-ly-tumble-dry-no-heat-delicate
    - pe-ly-tumble-dry-no-heat-resistant
    - pe-ly-tumble-dry-no-heat
    - pe-ly-tumble-dry-resistant
    - pe-ly-tumble-dry
    - pe-ly-wring
  languages:
    rs:
      name: Srpski
      code: rs
      currencyCode: RSD
      locale: sr_RS
      translation: serbian
    en:
      name: Engleski
      code: en
      currencyCode: RSD
      locale: en_AT
      translation: english
#    ba:
#      name: Bosanski
#      code: ba
#      currencyCode: BAM
  countries:
    rs:
      name: serbia
      code: rs
  site_info_texts:
    cookie_policy:
      title: navi.cookie_policy
      type: cookie_policy
      path: site.cookie_policy
      slug:
        rs: politika-kolacica
        en: cookie-policy
    policy_and_privacy:
      title: navi.policy_and_privacy
      type: policy_and_privacy
      slug:
        rs: politika-privatnosti
        en: privacy-policy
    use_conditions:
      title: navi.use_conditions
      type: use_conditions
      slug:
        rs: uslovi-koriscenja
        en: use-conditions
    withdraw_policy:
      title: navi.withdraw_policy
      type: withdraw_policy
      slug:
        rs: pravo-na-odustajanje
        en: withdraw-policy
    complaint:
      title: navi.complaint
      type: complaint
      slug:
        rs: reklamacije
        en: complaint
    payment_methods:
      title: navi.payment_methods
      type: payment_methods
      slug:
        rs: nacin-placanja
        en: payment-methods
    delivery:
      title: navi.delivery
      type: delivery
      slug:
        rs: dostava
        en: delivery
    free_delivery:
      title: navi.free_delivery
      type: free_delivery
      slug:
        rs: besplatna-dostava
        en: Free delivery
    in_store_pickup:
      title: navi.in_store_pickup
      type: in_store_pickup
      slug:
        rs: preuzimanje-u-radnji
        en: in-store-pickup
    product_rehearsal:
      title: navi.product_rehearsal
      type: product_rehearsal
      slug:
        rs: proba-proizvoda
        en: product-rehearsal
    product_return_and_exchange:
      title: navi.product_return_and_exchange
      type: product_return_and_exchange
      slug:
        rs: zamena-i-povrat-robe
        en: product-return-and-exchange
    refund:
      title: navi.refund
      type: refund
      slug:
        rs: povracaj-novca
        en: refund
    about_us:
      title: navi.about_us
      type: about_us
      slug:
        rs: o-nama
        en: about-us
