framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    translator:
        enabled_locales: ['rs', 'en']
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(DEFAULT_LOCALE)%'
