framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    enabled_locales: ['rs', 'en', 'ba']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(DEFAULT_LOCALE)%'
