twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        default_alt_tag: 'Elipsa - modna kuca'
        default_title_tag: 'Elipsa - modna kuca'
        cleaning: '%cleaning%'
        fb_id: '%env(resolve:FB_ID)%'
        intesa_gateway: '%env(resolve:GATEWAY)%'
        intesa_merchant_id: '%env(resolve:MERCHANT_ID)%'
        intesa_store_key: '%env(resolve:STORE_KEY)%'