version: '3.6'
services:
  lamp:
    build: ./docker/lamp
    image: lamp
    container_name: elipsa-lamp
    ports:
      - "9600:80"
    volumes:
      - "./:/var/www/html:rw,cached"
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=local"
      XDEBUG_SESSION: "PHPSTORM"

  mysql:
    image: mariadb:10
    hostname: elipsa-mysql
    container_name: elipsa-mysql
    volumes:
      - "mysql-mount:/var/lib/mysql:rw,cached"
    ports:
      - "9601:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vlada123!!!
      - MYSQL_DATABASE=elipsa

  elipsa-phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: elipsa-phpmyadmin
    restart: always
    ports:
      - '9602:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vlada123!!!

  elipsa-mailcatcher:
    image: schickling/mailcatcher
    container_name: elipsa-mailcatcher
    ports:
      - "9603:1025" # changed to 1026 to avoid local instance of mailcatcher
      - "9604:1080"

volumes:
#  elipsa-sync:
#    external: true
  mysql-mount:
