version: '3.6'
services:
  elipsa-lamp:
    build: ./docker/lamp
    image: lamp
    container_name: elipsa-lamp
    ports:
      - "9091:80"
    volumes:
      - "./:/var/www/html:rw"
    depends_on:
      - elipsa-mysql
    networks:
      elipsa-network:
        ipv4_address: 172.26.0.10

  elipsa-mysql:
    build: ./docker/mysql
    image: mysql
    container_name: elipsa-mysql
    volumes:
      - "./docker/mysql-mount:/var/lib/mysql:rw"
    ports:
      - "63307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vlada123!!!
      - MYSQL_DATABASE=elipsa
      - MYSQL_USER=vlada
      - MYSQL_PASSWORD=vlada
    networks:
      elipsa-network:
        ipv4_address: 172.26.0.2

  elipsa-phpmyadmin:
    depends_on:
      - elipsa-mysql
    image: phpmyadmin/phpmyadmin
    container_name: elipsa-phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vlada123!!!
    networks:
      elipsa-network:
        ipv4_address: 172.26.0.3
      
  elipsa-mailcatcher:
    image: schickling/mailcatcher
    container_name: elipsa-mailcatcher
    ports:
      - "1027:1025" # changed to 1026 to avoid local instance of mailcatcher
      - "1082:1080"
    networks:
      elipsa-network:
        ipv4_address: 172.26.0.4

networks:
  elipsa-network:
    name: elipsa-network
    ipam:
      config:
        - subnet: 172.26.0.0/24