version: '3.6'
services:
  elipsa-lamp:
    build: ./docker/lamp
    image: lamp
    container_name: elipsa-lamp
    ports:
      - "9191:80"
    volumes:
      - "./:/var/www/html:rw"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4.10
    hostname: elipsa-mysql
    container_name: elipsa-mysql
    volumes:
      - "./docker/mysql:/var/lib/mysql:rw"
    ports:
      - "63307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vlada123!!!
      - MYSQL_DATABASE=elipsa

  elipsa-phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: elipsa-phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vlada123!!!

  elipsa-mailcatcher:
    image: schickling/mailcatcher
    container_name: elipsa-mailcatcher
    ports:
      - "1027:1025" # changed to 1026 to avoid local instance of mailcatcher
      - "1082:1080"

volumes:
  mysql-data: