controllers_site:
    resource: ../../src/Controller/Site/
    type: attribute
    host:
        rs: '%host_rs%'
        ba: '%host_ba%'
        en: ''
    prefix:
        rs: ''
        ba: ''
        en: '/en'

controllers_unique:
    resource: ../../src/Controller/Unique/
    type: attribute
    host:
        rs: '%host_rs%'
        ba: '%host_ba%'
        en: ''
    prefix:
        rs: ''
        ba: ''
        en: '/en'

controllers_admin:
    resource: ../../src/Controller/Admin/
    type: attribute
    prefix: /admin
    options:
        expose: true

kernel:
    resource: ../../src/Kernel.php
    type: attribute
