#admin.dashboard:
#  path: /
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#  defaults:
#    template: Admin/Pages/dashboard.html.twig

admin.colors:
  path: /colors
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/colors.html.twig

admin.product_tags:
  path: /product-tags
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/tags.html.twig

admin.categories:
  path: /categories
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/categories.html.twig

admin.sizes:
  path: /sizes
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/sizes.html.twig

admin.sliders:
  path: /sliders
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/sliders.html.twig

admin.home_banners:
  path: /home-banners
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/homeBanners.html.twig

admin.promotion_coupons:
  path: /promotion/coupons
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/promotions.html.twig
    context:
      title: Promotivni kuponi
      add_promotion_page_name: admin.add_promotion_coupon_page
      edit_promotion_page_name: admin.edit_promotion_coupon_page
      list_api_url: admin.get_promotion_coupons_list

admin.promotion_products:
  path: /promotion/products
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/promotions.html.twig
    context:
      title: Promocije proizvoda
      add_promotion_page_name: admin.add_promotion_product_page
      edit_promotion_page_name: admin.edit_promotion_product_page
      list_api_url: admin.get_promotion_products_list

admin.locations:
  path: /locations
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/locations.html.twig

admin.blog:
  path: /blog
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/blog.html.twig

admin.blog_tags:
  path: /blog-tags
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/tags.html.twig

admin.loyalty:
  path: /loyalty
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/loyalty.html.twig

admin.collaborators:
  path: /collaborators
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/collaborators.html.twig

admin.career:
  path: /career
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/careerApplicationView.html.twig

admin.slider_text:
  path: /slider-text
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/sliderText.html.twig

admin.office_contacts:
  path: /office-contact
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/officeContacts.html.twig

admin.orders:
  path: /orders
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/orders.html.twig

admin.banners:
  path: /banners
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/banners.html.twig

admin.login:
  path: /login
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/login.html.twig

admin.logout:
  path: /logout

admin.users:
  path: /users
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/users.html.twig

admin.descriptions:
  path: /description
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/descriptions.html.twig

admin.jobs:
  path: /jobs
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/jobs.html.twig

admin.catalog_page:
  path: /catalog
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/catalog.html.twig
