site.loyalty:
  path:
    rs: /loyalty
    en: /en/loyalty
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/loyalty.html.twig
  options:
    expose: true

site.registration:
  path:
    rs: /registracija
    en: /en/registration
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/registration.html.twig
  options:
    expose: true

site.registration_confirmation:
  path:
    rs: /uspesna-registracija
    en: /en/success-registration
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/registrationSuccess.html.twig
  options:
    expose: true

site.collaborator:
  path:
    rs: /saradnici
    en: /en/collaborators
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/collaborator.html.twig

site.policy_page:
  path:
    rs: /politika-privatnosti
    en: /en/privacy-policy
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/privacy_policy.html.twig

site.cookie_policy:
  path:
    rs: /politika-kolacica
    en: /en/cookie-policy
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/cookie_policy.html.twig
  options:
    expose: true

site.use_conditions:
  path:
    rs: /uslovi-koriscenja
    en: /en/use-conditions
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/use_condition.html.twig

site.cart_page:
  path:
    rs: /korpa
    en: /en/cart
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/cart.html.twig

site.checkout_page:
  path:
    rs: /korpa/unos-podataka
    en: /en/checkout
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/checkout.html.twig

site.facebook_login:
  path: /login/check/facebook

site.google_login:
  path: /login/check/google

site.logout:
  path: /logout

site.not_exists_page:
  path:
    rs: /nepostojeca-stranica
    en: /en/not-exits-page
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/404Page.html.twig

site.robots:
  path: /robots.txt
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/robots.txt.twig

