site.checkout_completed_successful:
  path:
    rs: /korpa/uspesna-narudzbina
    en: /{_locale}/cart/success-order
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/checkoutComplete.html.twig
  options:
    expose: true

site.loyalty:
  path:
    rs: /loyalty
    en: /{_locale}/loyalty
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Site/Pages/loyalty.html.twig