#index:
#    path: /
#    controller: App\Controller\DefaultController::index

_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
  prefix: '/translator'

admin:
  resource: 'routes/routes_admin.yaml'
  prefix: /admin
  options:
    expose: true

site:
  resource: 'routes/routes_site.yaml'
  host:
    rs: '%host_rs%'
    ba: '%host_ba%'
    en: ''
  options:
    expose: true

site.product_page:
  host:
    rs: '%host_rs%'
    ba: '%host_ba%'
    en: ''
  path:
    rs: /{slug}
    ba: /{slug}
    en: /{_locale}/{slug}
  defaults: { _controller: App\Controller\Site\ProductPageController::index}
  options:
    expose: true
