# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: "../vendor/beberlei/doctrineextensions/config/mysql.yml" }
parameters:
    .container.dumper.inline_factories: true
    # rs must be first language
    locales: ['rs', 'en', 'ba']
    upload_dir: '%kernel.project_dir%/storage/'
    upload_tmp_dir: 'tmp/'
    upload_image_dir: 'image/'
    upload_import_dir: 'import/images/'
    upload_document_dir: 'documents/'
    url: '%env(resolve:SITE_SCHEME)%://%env(resolve:URL)%/'

    intesa_merchant_id: '%env(resolve:MERCHANT_ID)%'
    intesa_store_key: '%env(resolve:STORE_KEY)%'
    intesa_user_name: '%env(resolve:USERNAME)%'
    intesa_password: '%env(resolve:PASSWORD)%'
    intesa_api_gateway: '%env(resolve:API_GATEWAY)%'


    google_recaptcha_secret: '%env(resolve:GOOGLE_RECAPTCHA_KEY_SECRET)%'

    router.request_context.host: '%env(resolve:SITE_URL)%'
    router.request_context.scheme: '%env(resolve:SITE_SCHEME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $defaultLocale: '%env(resolve:DEFAULT_LOCALE)%'
            $locales: '%locales%'
            $siteInfoText: '%site_info_texts%'
            $languages: '%languages%'
            $googleRecaptchaSecret: '%env(GOOGLE_RECAPTCHA_KEY_SECRET)%'
            $shopOptions: '%shop%'
            $countries: '%countries%'
            $googleApiKey: '%env(GOOGLE_MAPS_API)%'
            $adminLocale: '%env(DEFAULT_LOCALE)%'

    _instanceof:
        App\Checker\NotificationCheckerInterface:
            tags: ['app.checker.notification']
        App\Checker\PromotionCheckerInterface:
            tags: ['app.checker.promotion']
        App\Checker\PromotionOptionCheckerInterface:
            tags: ['app.checker.promotion_option']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php, ImageResizer.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Repository\ExtendedEntityRepository:
        arguments:
            $entityClass: ~

    Liip\ImagineBundle\Service\FilterService:
        alias: 'liip_imagine.service.filter'

    Turanjanin\SerbianTransliterator\Transliterator: ~

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
              - { name: doctrine.event_listener, event: 'prePersist' }
              - { name: doctrine.event_listener, event: 'onFlush' }
              - { name: doctrine.event_listener, event: 'loadClassMetadata' }

    App\EventListener\ImageFileSystemListener:
        class: App\EventListener\ImageFileSystemListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    App\EventListener\RequestEventListener:
        class: App\EventListener\RequestEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\FilterRequestEventListener:
        class: App\EventListener\FilterRequestEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\ResponseEventListener:
        class: App\EventListener\ResponseEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    app.sitemap_ads_listener:
        class: App\EventListener\SiteMapProductsSubscriber
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap_listener:
        class: App\EventListener\SiteMapStaticSubscriber
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap_tag_listener:
        class: App\EventListener\SiteMapTagsSubscriber
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap_blog_listener:
        class: App\EventListener\SiteMapBlogSubscriber
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    App\EventListener\OrderShippingPriceEventListener:
        tags:
            - { name: doctrine.orm.entity_listener }


    App\EventListener\PromotionTagEventListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    App\Parser\Site\NotificationRequestParser:
        arguments:
            $checkers: !tagged_iterator app.checker.notification

    App\Checker\PromotionCouponChecker:
        arguments:
            $promotionCheckers: !tagged_iterator app.checker.promotion
            $promotionOptionCheckers: !tagged_iterator app.checker.promotion_option

    App\Checker\PromotionProductChecker:
        arguments:
            $promotionCheckers: !tagged_iterator app.checker.promotion
            $promotionOptionCheckers: !tagged_iterator app.checker.promotion_option

    App\Checker\PromotionFreeShippingChecker:
        arguments:
            $promotionCheckers: !tagged_iterator app.checker.promotion
            $promotionOptionCheckers: !tagged_iterator app.checker.promotion_option
